# Need super user permission for docker
sudo: required
# Need docker to run
services:
  - docker

# Before running test
before_install:
  - docker build -t praja/docker-react -f Dockerfile.dev .

script:
  - docker run praja/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-133054347778"
  bucket_path: "docker-react" #app name
  on: 
    branch: "master"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET"